### ISSUE TITLE
Used non pythonic way

### ISSUE THREAD

**Issue by gau1991** [Riser101/python-assignment-rtcamp#2]
Hi,
You used most of shell commands in your script. Such as following part of your code:

```
os.system('ln -s /etc/nginx/sites-available/'+domainName+' /etc/nginx/sites-enabled/')
os.system('mkdir -p /var/www/'+domainName+'/htdocs/ /var/www/'+domainName+'/logs/ && cd /var/www/'+domainName+'/htdocs/')
os.system('wget http://wordpress.org/latest.tar.gz')
os.system('tar --strip-components=1 -xvf latest.tar.gz && rm latest.tar.gz')
os.system('chown -R www-data:www-data /var/www/'+domainName+'/ ')
```

instead of `os.system("shell command")` you must use python functions to all this.

**Comment by riser101** [comment]
@gau1991 Addressed, please check.

**Comment by gau1991** [comment]
Hi @Riser101 ,
In your install script you are still using Non pythonic way:

```
os.system('pip install PyMySQL')
```

**Comment by riser101** [comment]
Hello @gau1991 
Install script updated, let me know if anything else needs to be straigtened up. Thank you.
